stages:          
  - build
  - deploy

build-job:
  stage: build  
  image: node:20.9.0
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - "www/"

pages:
  stage: deploy 
  script:
    - mv www/ public/
  artifacts:
    paths:
      - "public/"